// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmRSQNf3D5orS8mofLMCFzncbtizX1r4',
    appId: '1:590543154350:web:413052863d2d4fd72b513f',
    messagingSenderId: '590543154350',
    projectId: 'mentalhealthcare-2b62f',
    authDomain: 'mentalhealthcare-2b62f.firebaseapp.com',
    storageBucket: 'mentalhealthcare-2b62f.appspot.com',
    measurementId: 'G-35E1Q8CMTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlaNyB335uDGSGwqn5ENwxGjOtmyDwswE',
    appId: '1:590543154350:android:38a5310ef15774792b513f',
    messagingSenderId: '590543154350',
    projectId: 'mentalhealthcare-2b62f',
    storageBucket: 'mentalhealthcare-2b62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4y_nmbGWe9BOV3z2KSz8uwAjIiUXDKDs',
    appId: '1:590543154350:ios:73b5dd957602d8c92b513f',
    messagingSenderId: '590543154350',
    projectId: 'mentalhealthcare-2b62f',
    storageBucket: 'mentalhealthcare-2b62f.appspot.com',
    iosBundleId: 'com.example.mentalhealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4y_nmbGWe9BOV3z2KSz8uwAjIiUXDKDs',
    appId: '1:590543154350:ios:73b5dd957602d8c92b513f',
    messagingSenderId: '590543154350',
    projectId: 'mentalhealthcare-2b62f',
    storageBucket: 'mentalhealthcare-2b62f.appspot.com',
    iosBundleId: 'com.example.mentalhealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjmRSQNf3D5orS8mofLMCFzncbtizX1r4',
    appId: '1:590543154350:web:c20849561e5c88f72b513f',
    messagingSenderId: '590543154350',
    projectId: 'mentalhealthcare-2b62f',
    authDomain: 'mentalhealthcare-2b62f.firebaseapp.com',
    storageBucket: 'mentalhealthcare-2b62f.appspot.com',
    measurementId: 'G-X9ZMB1264W',
  );
}
